# Generated by Django 5.2.13 on 2026-05-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_exam_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='knowledge_point',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
