# Generated by Django 5.2.13 on 2026-05-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_question_knowledge_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
