# Generated by Django 6.0.4 on 2026-04-27 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subject_user_real_name_exam_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.JSONField(default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_correct'], name='api_student_student_16ddf1_idx'), models.Index(fields=['question', 'is_correct'], name='api_student_questio_0ceae2_idx')],
                'unique_together': {('question', 'student')},
            },
        ),
    ]
